<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>

        <!-- Preferred -->
        <TargetFramework>net10.0</TargetFramework>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <AssemblyName>BluetoothHandsFreeToggle</AssemblyName>
        <RootNamespace>BluetoothHandsFreeToggle</RootNamespace>

        <!-- Quality-of-life -->
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <!-- ServiceController API for Windows services -->
        <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
    </ItemGroup>

</Project>
