namespace BluetoothHandsFreeToggle.Localization;

public enum AppLanguage
{
    English = 0,
    Russian = 1,
    ChineseSimplified = 2,
    ChineseTraditional = 3,
    German = 4,
    French = 5,
    SpanishSpain = 6,
    SpanishLatinAmerica = 7,
    PortugueseBrazil = 8,
    PortuguesePortugal = 9,
    Japanese = 10,
    Korean = 11,
    Polish = 12,
    Turkish = 13,
    Italian = 14,
    Thai = 15,
    Ukrainian = 16,
    Czech = 17,
    Dutch = 18,
    Swedish = 19,
    Danish = 20,
    NorwegianBokmal = 21,
    Finnish = 22,
    Hungarian = 23,
    Romanian = 24,
    Greek = 25,
    Bulgarian = 26,
    Indonesian = 27,
    Malay = 28,
    Vietnamese = 29
}
